model:
  input_size: 1
  hidden_size: 32
  output_size: 1
  layer_count: 3
  freq: 10
  activation: tanh
  activation_init: 0.6
  use_mask: true

physics:
  m: 2
  k: 200
  c: 2
  x0: 0.5
  v0: 0.0
  alpha_actual: 0.6
  T: 20.0
  tau_actual: 12.0
  dt: 0.01
  force_mag: 1.0

training:
  seed: 123
  mode: alpha
  alpha_steps: 10000
  tau_steps: 10000
#  resume_path: artifacts/checkpoints/alpha/mask_step_6.pth
  resume_path: null
  alpha_init: 0.9
  tau_init: 13.0
  clamp_min: 0.1
  clamp_max: 0.99
  lr_pinn: 0.001
  lr_tau: 0.1
  lr_alpha: 0.001
  lam1: 0.004
  lam2: 0.1
  noise_std: 0.02
  t_phy_points: 2000
  t_test_points: 1000
  t_obs_points: 1000

artifacts:
  save_dir: artifacts
  fps: 10
  fig_size: [15, 20]
  plot_every: 40
  gif_every: 80
  ckpt_every: 200
  gif_dir: gif
  ckpt_dir: checkpoints
  plots_dir: plots